services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    container_name: ${COMPOSE_PROJECT_NAME}_app
    command: ["sh", "-c", "/usr/local/bin/start.sh"]
    restart: on-failure
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/supervisord.conf:/etc/supervisor/supervisord.conf
      - .env:/var/www/.env
    networks:
      - symfony-network
    ports:
      - "9000:9000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - symfony-network

  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony-network

  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: on-failure
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 60s
    ports:
      - "6379:6379"
    networks:
      - symfony-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    restart: on-failure
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog_data:/maildir
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  mailhog_data:
    driver: local
